// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (user_id, datetime, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, datetime, title, description, status, created_at
`

type CreateAppointmentParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Datetime    pgtype.Timestamptz `json:"datetime"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.UserID,
		arg.Datetime,
		arg.Title,
		arg.Description,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Datetime,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, phone, is_admin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, password_hash, phone, is_admin, created_at
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Phone        string `json:"phone"`
	IsAdmin      bool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointment, id)
	return err
}

const getAllAppointments = `-- name: GetAllAppointments :many
SELECT
  a.id,
  a.user_id,
  a.datetime,
  a.title,
  a.description,
  a.status,
  a.created_at,
  u.name AS user_name,
  u.email AS user_email,
  u.phone AS user_phone
FROM appointments a
JOIN users u ON a.user_id = u.id
ORDER BY a.created_at DESC
`

type GetAllAppointmentsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Datetime    pgtype.Timestamptz `json:"datetime"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    string             `json:"user_name"`
	UserEmail   string             `json:"user_email"`
	UserPhone   string             `json:"user_phone"`
}

func (q *Queries) GetAllAppointments(ctx context.Context) ([]GetAllAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, getAllAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAppointmentsRow
	for rows.Next() {
		var i GetAllAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Datetime,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByID = `-- name: GetAppointmentsByID :one
SELECT id, user_id, datetime, title, description, status, created_at FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointmentsByID(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentsByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Datetime,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAppointmentsForUser = `-- name: GetAppointmentsForUser :many
SELECT id, user_id, datetime, title, description, status, created_at FROM appointments WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAppointmentsForUser(ctx context.Context, userID pgtype.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Datetime,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, phone, is_admin, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, phone, is_admin, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE users SET is_admin = $2 WHERE email = $1
`

type SetAdminParams struct {
	Email   string `json:"email"`
	IsAdmin bool   `json:"is_admin"`
}

func (q *Queries) SetAdmin(ctx context.Context, arg SetAdminParams) error {
	_, err := q.db.Exec(ctx, setAdmin, arg.Email, arg.IsAdmin)
	return err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :exec
UPDATE appointments SET status = $2 WHERE id = $1
`

type UpdateAppointmentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAppointmentStatus, arg.ID, arg.Status)
	return err
}

const userUpdateAppointment = `-- name: UserUpdateAppointment :exec
UPDATE appointments SET datetime = $2, title = $3, description = $4 WHERE user_id = $5 AND id = $1
`

type UserUpdateAppointmentParams struct {
	ID          pgtype.UUID        `json:"id"`
	Datetime    pgtype.Timestamptz `json:"datetime"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UserUpdateAppointment(ctx context.Context, arg UserUpdateAppointmentParams) error {
	_, err := q.db.Exec(ctx, userUpdateAppointment,
		arg.ID,
		arg.Datetime,
		arg.Title,
		arg.Description,
		arg.UserID,
	)
	return err
}
